-- \COPY podcasts FROM 'podcasts.csv' with (FORMAT CSV, HEADER, DELIMITER '|');

DROP TABLE IF EXISTS podcasts;

CREATE TABLE podcasts (
    id INTEGER PRIMARY KEY,
    url TEXT NOT NULL UNIQUE,
    title TEXT,
    lastUpdate INTEGER,
    link TEXT,
    lastHttpStatus INTEGER,
    dead INTEGER,
    contentType TEXT,
    itunesId INTEGER,
    originalUrl TEXT,
    itunesAuthor TEXT,
    itunesOwnerName TEXT,
    explicit INTEGER,
    imageUrl TEXT,
    itunesType TEXT,
    generator TEXT,
    newestItemPubdate INTEGER,
    language TEXT,
    oldestItemPubdate INTEGER,
    episodeCount INTEGER,
    popularityScore INTEGER,
    priority INTEGER,
    createdOn INTEGER,
    updateFrequency INTEGER,
    chash TEXT,
    host TEXT,
    newestEnclosureUrl TEXT,
    podcastGuid TEXT,
    description TEXT,
    category1 TEXT,
    category2 TEXT,
    category3 TEXT,
    category4 TEXT,
    category5 TEXT,
    category6 TEXT,
    category7 TEXT,
    category8 TEXT,
    category9 TEXT,
    category10 TEXT,
    newestEnclosureDuration INTEGER
);