name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGION: us-east-1
      INSTANCE_TYPE: g4dn.xlarge
      KEY_NAME: transcription_key
      SECURITY_GROUP_ID: sg-0ead103f191c31c90
      SUBNET_ID: subnet-0d35ca21bbec62faa
      ROLE_ARN: arn:aws:iam::381492150662:instance-profile/ec2-instance-role-profile

    permissions:
      id-token: write
      contents: read


    steps:
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_DEV_GITHUB_ACTION_ROLE }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      run: aws ecr get-login-password --region ${{ vars.REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ vars.REGION }}.amazonaws.com

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Determine the image tag
      run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Check if the Docker image already exists in ECR
      id: ecr_image_check
      run: |
        REPOSITORY_URI=${{ secrets.ECR_REPOSITORY }}
        REPOSITORY_NAME=$(basename $REPOSITORY_URI)
        IMAGE_TAG=${{ env.IMAGE_TAG }}
        
        # Check if the image exists
        aws ecr describe-images --repository-name $REPOSITORY_NAME --image-ids imageTag=$IMAGE_TAG && \
          echo "IMAGE_EXISTS=true" >> $GITHUB_ENV || \
          echo "IMAGE_EXISTS=false" >> $GITHUB_ENV

    - name: Build and push Docker image only if it doesn't exist
      if: env.IMAGE_EXISTS == 'false'
      run: |
        IMAGE_TAG=${{ env.IMAGE_TAG }}
        REPOSITORY_URI=${{ secrets.ECR_REPOSITORY }}
        docker build -t $REPOSITORY_URI:$IMAGE_TAG .
        docker push $REPOSITORY_URI:$IMAGE_TAG

    - name: Launch EC2 Instance
      id: launch_ec2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ${{ secrets.AMI_ID }} \
          --instance-type ${{ env.INSTANCE_TYPE }} \
          --key-name ${{ env.KEY_NAME }} \
          --security-group-ids ${{ env.SECURITY_GROUP_ID }} \
          --subnet-id ${{ env.SUBNET_ID }} \
          --iam-instance-profile Arn=${{ env.ROLE_ARN }} \
          --query 'Instances[0].InstanceId' \
          --output text)
        
        echo "EC2 instance ID: $INSTANCE_ID"
        echo "::set-output name=instance_id::$INSTANCE_ID"

    - name: Wait for EC2 Instance to be running
      run: |
        aws ec2 wait instance-running --instance-ids ${{ steps.launch_ec2.outputs.instance_id }}

    - name: Retrieve EC2 Public IP
      id: get_ip
      run: |
        PUBLIC_IP=$(aws ec2 describe-instances \
          --instance-ids ${{ steps.launch_ec2.outputs.instance_id }} \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)
        echo "EC2 instance public IP: $PUBLIC_IP"
        echo "::set-output name=public_ip::$PUBLIC_IP"

    - name: Wait for SSH to be available
      run: |
        echo "Waiting for SSH on the EC2 instance to be available..."
        sleep 60  # Adjust based on how long your instance takes to be ready for SSH

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Get GitHub Actions runner's public IP
      id: get_runner_ip
      run: |
        RUNNER_IP=$(curl -s http://checkip.amazonaws.com)
        echo "RUNNER_IP=$RUNNER_IP" >> $GITHUB_ENV
      shell: bash

    - name: Add GitHub Actions runner's IP to security group
      run: |
        aws ec2 authorize-security-group-ingress \
          --group-id ${{ env.SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr $RUNNER_IP/32

    - name: Deploy Docker image to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ steps.get_ip.outputs.public_ip }} << 'EOF'
          IMAGE_TAG=${{ env.IMAGE_TAG }}

          docker login -u AWS -p $(aws ecr get-login-password --region ${{ vars.REGION }}) ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ vars.REGION }}.amazonaws.com

          # Pull the image with the specific commit hash tag
          docker pull ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

          # Run the new container with the same settings from docker-compose
          docker run -d \
            --name my-service \
            -p 80:80 \
            -p 443:443 \
            --gpus all \
            -e NVIDIA_VISIBLE_DEVICES=all \
            -e NVIDIA_DRIVER_CAPABILITIES=compute,utility \
            ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
        EOF

    - name: Remove GitHub Actions runner's IP from security group
      if: always()
      run: |
        aws ec2 revoke-security-group-ingress \
          --group-id ${{ env.SECURITY_GROUP_ID }} \
          --protocol tcp \
          --port 22 \
          --cidr $RUNNER_IP/32
